# Generated by Django 4.2.7 on 2024-01-05 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mymodel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid_field', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
